#!/usr/local/bin/busybox sh

# needed for some binaries
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

BIN=/usr/local/bin/busybox


# disable kernel logging to stdout...
$BIN dmesg -n 1


# proc, sysfs
$BIN mount -t proc proc /proc
$BIN mount -n -t sysfs -o nodev,noexec,nosuid sysfs /sys


# devfs
$BIND mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null || $BIN mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev

[ -c /dev/ptmx ] || $BIN mknod -m 666 /dev/ptmx c 5 2

[ -d /dev/pts ] || $BIN mkdir -m 755 /dev/pts
$BIN mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts


# shared memory area (later system will need it)
[ -d /dev/shm ] || $BIN mkdir /dev/shm
$BIN mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm


# cgroup
$BIN mount -n -t tmpfs -o nodev,noexec,nosuid,mode=755,size=64k cgroup_root /sys/fs/cgroup
$BIN mount -t cgroup2 none /sys/fs/cgroup/            # cgroup v2 kernel 5.x
#mount -t cgroup -o all cgroup /sys/fs/cgroup # cgroup v1


# detect hardware and initialize drivers
$BIN grep -h MODALIAS /sys/bus/*/devices/*/uevent | $BIN cut -d= -f2 | $BIN xargs modprobe -abq 2> /dev/null
$BIN grep -h MODALIAS /sys/bus/*/devices/*/uevent | $BIN cut -d= -f2 | $BIN xargs modprobe -abq 2> /dev/null


# create rootfs partition (tmpfs)
ROOTFS=/newroot
$BIN mkdir $ROOTFS
#mount -t tmpfs -o size=100m tmpfs /newroot
$BIN mount -t tmpfs tmpfs $ROOTFS

(
    cd $ROOTFS && \
    $BIN mkdir -p \
	bin \
	etc \
	run \
	tmp \
	dev \
	sys \
	proc \
	sbin \
	var/lib \
	var/log \
	usr/bin \
	usr/sbin \
	lib/firmware \
	usr/local/bin
)

$BIN cp -a /lib /etc $ROOTFS/
$BIN cp -a /usr/local/bin/* $ROOTFS/usr/local/bin/

$BIN chroot $ROOTFS /usr/local/bin/busybox --install -s

$BIN rm -f $ROOTFS/linuxrc

$BIN chroot $ROOTFS ln -s /run /var/run
$BIN chroot $ROOTFS ln -s /tmp /var/tmp
$BIN chroot $ROOTFS ln -s /usr/local/bin/* /bin/



# unpack newrootfs
#tar -xf /newrootfs.tar -C $ROOTFS

# base containers OR persistent mount for /containers
$BIN tar -xf /containers.tar -C $ROOTFS/


# prepare switch root 
$BIN mount --move /sys $ROOTFS/sys
$BIN mount --move /proc $ROOTFS/proc
$BIN mount --move /dev $ROOTFS/dev

### Workarounds switch_root prepare...
#rm -f $ROOTFS/linuxrc 
#cp -a /etc/inittab $ROOTFS/etc/inittab
#cp -a /lib/* $ROOTFS/lib/
$BIN mkdir -p $ROOTFS/run/resolvconf
$BIN touch $ROOTFS/run/resolvconf/resolv.conf

# leave initrd, use newroot
exec $BIN switch_root $ROOTFS  $BIN init
